### PR TITLE
Thai/bower gwm

### PR DESCRIPTION
**Pull request by athai**
@tschuy

### CODE REVIEW

**Comment by tschuy** [comment]
Looks good! 

... but I forgot to mention some other packages we're storing minimized that you originally had on the list before I had you remove them. Ones without versions :cry: 

1. jquery tablesorter
2. ctyoscape

Can you add these back?

**Comment by tschuy** [comment]
Oh, and add some docs so that travis-ci will pass? https://travis-ci.org/osuosl/ganeti_webmgr/builds/69981513

Perhaps something in the dev/development.rst file, under Submitting Code, about preferring packages on bower?

**Comment by athai** [comment]
Where is tablesorter used?

**Comment by tschuy** [comment]
:+1: you can merge it :smile:

**Pull request merged**
