### PR TITLE
Fix LDAP support

### PR DESCRIPTION
**Pull request by tschuy**
The settings import is broken, and the documentation needs updating.

### CODE REVIEW

**Comment by Kennric** [comment]
Do we have a replacement for the tarfile script in the fabfile?

**Comment by tschuy** [comment]
I personally package GWM using Github's built-in tarring mechanism. I didn't even realize the fabfile did tarring until I went to get rid of it.

Github includes things like the Vagrantfile that the tarfile script excludes implicitly, but it's not too bad.

**Comment by Kennric** [comment]
Regarding the fabfile, let's make sure our documentation says where to get the tar file, and make sure one can download and install gwm from github's tarfile, using the existing documentation (or update the docs to fit).

**Comment by tschuy** [comment]
The docs currently do mention being able to get the tarball from Github:

```
#. Next you need the latest release of |gwm| which is |release|. You can
   download that here: |release_tarball|. You can also clone the repo and
   checkout the latest tag as well::
```

|release| and |release_tarball| are from conf.py, which has them currently set to 0.11.0 and and the link to that on Github respectively.

What I should add is documentation mentioning updating the docs to the release docs.

**Comment by Kennric** [comment]
+1

**Pull request merged**
